<?php

namespace Database\Seeders;

use App\Models\Asset;
use Illuminate\Database\Seeder;

class AssetsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $asset = Asset::create([
            'asset_tag' => 'Cable',
            'name' => 'Bend Insensitive Fiber Patch Cord',
            'description' => 'Bend Insensitive Fiber Patch Cord',
            'category_id' => 2,
            'brand' => '',
            'model' => '',
            'serial_number' => '',
            'barcode' => '',
            'qr_code' => '',
            'purchase_date' => '2025-11-17',
            'purchase_cost' => '160.00',
            'vendor_id' => 1,
            'invoice_number' => '',
            'purchase_order' => '',
            'warranty_expiry_date' => '2026-03-17',
            'warranty_months' => '12',
            'current_value' => '160.00',
            'salvage_value' => '0.00',
            'useful_life_years' => '1',
            'depreciation_method' => 'straight-line',
            'location_id' => 2,
            'department_id' => 3,
            'assigned_to' => 2,
            'assigned_at' => NULL,
            'status' => 'available',
            'condition' => 'excellent',
            'notes' => '',
            'image' => '',
            'is_critical' => 1,
            'next_maintenance_date' => '2026-02-21',
            'disposal_date' => NULL
        ]);

        $asset = Asset::create([
            'asset_tag' => 'CT2.4mm',
            'name' => 'Cable Tie 2.4 mm',
            'description' => 'Cable Tie 2.4 mm',
            'category_id' => 1,
            'brand' => '',
            'model' => '',
            'serial_number' => '',
            'barcode' => '',
            'qr_code' => '',
            'purchase_date' => '2025-11-18',
            'purchase_cost' => '610.00',
            'vendor_id' => 1,
            'invoice_number' => '',
            'purchase_order' => '',
            'warranty_expiry_date' => '2026-03-17',
            'warranty_months' => '12',
            'current_value' => '610.00',
            'salvage_value' => '0.00',
            'useful_life_years' => '1',
            'depreciation_method' => 'straight-line',
            'location_id' => 1,
            'department_id' => 3,
            'assigned_to' => 2,
            'assigned_at' => NULL,
            'status' => 'available',
            'condition' => 'excellent',
            'notes' => '',
            'image' => '',
            'is_critical' => 1,
            'next_maintenance_date' => '2026-02-22',
            'disposal_date' => NULL
        ]);

        $asset = Asset::create([
            'asset_tag' => 'FbrClpDp',
            'name' => 'Fiber Clamp Drop',
            'description' => 'Fiber Clamp Drop',
            'category_id' => 2,
            'brand' => '',
            'model' => '',
            'serial_number' => '',
            'barcode' => '',
            'qr_code' => '',
            'purchase_date' => '2025-11-18',
            'purchase_cost' => '215.00',
            'vendor_id' => 1,
            'invoice_number' => '',
            'purchase_order' => '',
            'warranty_expiry_date' => '2026-03-11',
            'warranty_months' => '12',
            'current_value' => '215.00',
            'salvage_value' => '0.00',
            'useful_life_years' => '1',
            'depreciation_method' => 'straight-line',
            'location_id' => 1,
            'department_id' => 3,
            'assigned_to' => 2,
            'assigned_at' => NULL,
            'status' => 'available',
            'condition' => 'excellent',
            'notes' => '',
            'image' => '',
            'is_critical' => 1,
            'next_maintenance_date' => '2026-02-25',
            'disposal_date' => NULL
        ]);

        $asset = Asset::create([
            'asset_tag' => 'SpanFTTH',
            'name' => 'Span Clamp for FTTH',
            'description' => 'Span Clamp for FTTH',
            'category_id' => 2,
            'brand' => '',
            'model' => '',
            'serial_number' => '',
            'barcode' => '',
            'qr_code' => '',
            'purchase_date' => '2025-11-18',
            'purchase_cost' => '215.00',
            'vendor_id' => 1,
            'invoice_number' => '',
            'purchase_order' => '',
            'warranty_expiry_date' => '2026-03-11',
            'warranty_months' => '12',
            'current_value' => '215.00',
            'salvage_value' => '0.00',
            'useful_life_years' => '1',
            'depreciation_method' => 'straight-line',
            'location_id' => 1,
            'department_id' => 3,
            'assigned_to' => 2,
            'assigned_at' => NULL,
            'status' => 'available',
            'condition' => 'excellent',
            'notes' => '',
            'image' => '',
            'is_critical' => 1,
            'next_maintenance_date' => '2026-02-25',
            'disposal_date' => NULL
        ]);

        $asset = Asset::create([
            'asset_tag' => 'Bracket1',
            'name' => 'Modified House Bracket',
            'description' => 'Modified House Bracket',
            'category_id' => 2,
            'brand' => '',
            'model' => '',
            'serial_number' => '',
            'barcode' => '',
            'qr_code' => '',
            'purchase_date' => '2025-11-18',
            'purchase_cost' => '215.00',
            'vendor_id' => 1,
            'invoice_number' => '',
            'purchase_order' => '',
            'warranty_expiry_date' => '2026-03-11',
            'warranty_months' => '12',
            'current_value' => '215.00',
            'salvage_value' => '0.00',
            'useful_life_years' => '1',
            'depreciation_method' => 'straight-line',
            'location_id' => 1,
            'department_id' => 3,
            'assigned_to' => 2,
            'assigned_at' => NULL,
            'status' => 'available',
            'condition' => 'excellent',
            'notes' => '',
            'image' => '',
            'is_critical' => 1,
            'next_maintenance_date' => '2026-02-25',
            'disposal_date' => NULL
        ]);

        $asset = Asset::create([
            'asset_tag' => 'ST3',
            'name' => 'Metal Screw With Tox ST3.9×38mm-6×30mm',
            'description' => 'Metal Screw With Tox ST3.9×38mm-6×30mm',
            'category_id' => 2,
            'brand' => '',
            'model' => '',
            'serial_number' => '',
            'barcode' => '',
            'qr_code' => '',
            'purchase_date' => '2025-11-18',
            'purchase_cost' => '215.00',
            'vendor_id' => 1,
            'invoice_number' => '',
            'purchase_order' => '',
            'warranty_expiry_date' => '2026-03-11',
            'warranty_months' => '12',
            'current_value' => '215.00',
            'salvage_value' => '0.00',
            'useful_life_years' => '1',
            'depreciation_method' => 'straight-line',
            'location_id' => 1,
            'department_id' => 3,
            'assigned_to' => 2,
            'assigned_at' => NULL,
            'status' => 'available',
            'condition' => 'excellent',
            'notes' => '',
            'image' => '',
            'is_critical' => 1,
            'next_maintenance_date' => '2026-02-25',
            'disposal_date' => NULL
        ]);

        $asset = Asset::create(attributes: [
            'asset_tag' => 'DropCable50M',
            'name' => 'Pre-Fabricated Drop cable 50M',
            'description' => 'Pre-Fabricated Drop cable 50M',
            'category_id' => 1,
            'brand' => '',
            'model' => '',
            'serial_number' => '',
            'barcode' => '',
            'qr_code' => '',
            'purchase_date' => '2025-11-18',
            'purchase_cost' => '215.00',
            'vendor_id' => 1,
            'invoice_number' => '',
            'purchase_order' => '',
            'warranty_expiry_date' => '2026-03-11',
            'warranty_months' => '12',
            'current_value' => '215.00',
            'salvage_value' => '0.00',
            'useful_life_years' => '1',
            'depreciation_method' => 'straight-line',
            'location_id' => 1,
            'department_id' => 3,
            'assigned_to' => 2,
            'assigned_at' => NULL,
            'status' => 'available',
            'condition' => 'excellent',
            'notes' => '',
            'image' => '',
            'is_critical' => 1,
            'next_maintenance_date' => '2026-02-25',
            'disposal_date' => NULL
        ]);

$asset = Asset::create(attributes: [
            'asset_tag' => 'DropCable100M',
            'name' => 'Pre-Fabricated Drop cable 100M',
            'description' => 'Pre-Fabricated Drop cable 100M',
            'category_id' => 1,
            'brand' => '',
            'model' => '',
            'serial_number' => '',
            'barcode' => '',
            'qr_code' => '',
            'purchase_date' => '2025-11-18',
            'purchase_cost' => '215.00',
            'vendor_id' => 1,
            'invoice_number' => '',
            'purchase_order' => '',
            'warranty_expiry_date' => '2026-03-11',
            'warranty_months' => '12',
            'current_value' => '215.00',
            'salvage_value' => '0.00',
            'useful_life_years' => '1',
            'depreciation_method' => 'straight-line',
            'location_id' => 1,
            'department_id' => 3,
            'assigned_to' => 2,
            'assigned_at' => NULL,
            'status' => 'available',
            'condition' => 'excellent',
            'notes' => '',
            'image' => '',
            'is_critical' => 1,
            'next_maintenance_date' => '2026-02-25',
            'disposal_date' => NULL
        ]);

        $asset = Asset::create(attributes: [
            'asset_tag' => 'DropCable150M',
            'name' => 'Pre-Fabricated Drop cable 150M',
            'description' => 'Pre-Fabricated Drop cable 150M',
            'category_id' => 1,
            'brand' => '',
            'model' => '',
            'serial_number' => '',
            'barcode' => '',
            'qr_code' => '',
            'purchase_date' => '2025-11-18',
            'purchase_cost' => '215.00',
            'vendor_id' => 1,
            'invoice_number' => '',
            'purchase_order' => '',
            'warranty_expiry_date' => '2026-03-11',
            'warranty_months' => '12',
            'current_value' => '215.00',
            'salvage_value' => '0.00',
            'useful_life_years' => '1',
            'depreciation_method' => 'straight-line',
            'location_id' => 1,
            'department_id' => 3,
            'assigned_to' => 2,
            'assigned_at' => NULL,
            'status' => 'available',
            'condition' => 'excellent',
            'notes' => '',
            'image' => '',
            'is_critical' => 1,
            'next_maintenance_date' => '2026-02-25',
            'disposal_date' => NULL
        ]);

        $this->command->info('Assets seeded successfully!');
    }
}
